### PR TITLE
Start clamp with a single command.

### PR DESCRIPTION
**Pull request by akkartik**

### CODE REVIEW

**Comment by malisper** [comment]
FYI, 90% of Common Lisp users use Slime.

**Comment by akkartik** [comment]
Thanks. I've been playing with Slime, and I added a couple of questions for you on the Forum.

What is your perspective on supporting people unfamiliar with Common Lisp and Slime? Totally fine if my comments, bug reports, pull requests are just annoying. I understand that you may not care about this project as much as when you first built it.

**Comment by malisper** [comment]
I answered the questions you left on the forum there: http://arclanguage.org/item?id=19854

I don't have any plan on how to support people unfamiliar with Common Lisp and Slime. It's well known in the Common Lisp community that you have to learn Emacs in order to get started and it doesn't seem that anyone cares enough to add Common Lisp to another editor. 

Although I think Clamp is interesting, I don't think I'm going to commit to it anytime soon, so I would suggest forking it so you could have complete control over it.

**Comment by akkartik** [comment]
Understood, thanks.

**Comment by akkartik** [comment]
I've taken the liberty of adding a fork at https://github.com/arclanguage/Clamp. It's not a GitHub fork, because that seemed more likely to send people with questions to you. Instead I linked to your repo in the description up top. Let me know if you'd like any changes to the setup, and I'll be happy to make them. Also let me know if you'd like to continue receiving Pull Requests for any changes there.

**Pull request merged**
